### ISSUE TITLE
add_adsorbate fails for linear molecules with 3 or more atoms

### ISSUE THREAD

**Issue by ehermes** [SUNCAT-Center/CatKit#81]
I ran into this issue when trying to adsorb linear molecules with three or more atoms. Here's a small example, adapted from the documentation:

```python
from catkit import Gratoms
from catkit.build import molecule
from catkit.gen.surface import SlabGenerator
from catkit.gen.adsorption import Builder
from catkit.gen.molecules import get_3D_positions

from ase.build import bulk
from ase.visualize import view

slab = SlabGenerator(bulk('Pd'),
                     miller_index=(1, 1, 1),
                     layers=8,
                     vacuum=4,
                     standardize_bulk=True).get_slab()

adsorbate = molecule('OCO', bond_index=1)[0]

ads_slab = Builder(slab).add_adsorbate(adsorbate, bonds=[1], index=-1)

print('{} adsorption structures generated'.format(len(ads_slab)))

view(ads_slab)
```

Produces the output:
```python-traceback
Traceback (most recent call last):
  File "bug.py", line 18, in <module>
    ads_slab = Builder(slab).add_adsorbate(adsorbate, bonds=[1], index=-1)
  File "/Users/ehermes/Library/Python/3.6/lib/python/site-packages/catkit/gen/adsorption.py", line 525, in add_adsorbate
    **kwargs)]
  File "/Users/ehermes/Library/Python/3.6/lib/python/site-packages/catkit/gen/adsorption.py", line 602, in _single_adsorption
    atoms, branch, root, adsorption=True)
  File "/Users/ehermes/Library/Python/3.6/lib/python/site-packages/catkit/gen/molecules.py", line 267, in _branch_molecule
    basis[:, 1] *= -np.sin(tor)
IndexError: index 1 is out of bounds for axis 1 with size 1
```

**Comment by jboes** [comment]
Hi ehermes,

Thanks for letting me know. I can't seem to reproduce this issue you are having which may suggest that it has already been fixed but not updated on pip. Try getting the most recent version from the master branch and see if that doesn't help.

**Comment by ehermes** [comment]
Thanks, switching to git master seems to have solved this issue for me.
